// Generated by scripts/generate-ai-quiz-context.mjs from canonical Quiz Markdown. Do not edit.
export const AI_QUIZ_CONTEXT = [
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "absorption",
    "type": "true-false",
    "prompt": "### 吸收律\n$A+AB=A$ 對所有布林值 $A,B$ 都成立。",
    "hint": null,
    "solution": "$A+AB=A(1+B)=A\\cdot1=A$。",
    "rubric": [],
    "correctAnswer": true
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "demorgan",
    "type": "multiple",
    "prompt": "### 選出所有恆等式\n以下哪些式子對所有 $A,B$ 都成立？",
    "hint": null,
    "solution": "前兩式是德摩根定律；第三式是互補律。$A\\overline A$ 永遠等於 $0$。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$\\overline{A+B}=\\overline A\\,\\overline B$"
      },
      {
        "id": "b",
        "content": "$\\overline{AB}=\\overline A+\\overline B$"
      },
      {
        "id": "c",
        "content": "$A+\\overline A=1$"
      },
      {
        "id": "d",
        "content": "$A\\overline A=1$"
      }
    ],
    "correctOptionIds": [
      "a",
      "b",
      "c"
    ]
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "double-negation",
    "type": "true-false",
    "prompt": "### 雙重否定\n$\\overline{\\overline A}=A$。",
    "hint": null,
    "solution": "對布林值取反兩次會得到原值。",
    "rubric": [],
    "correctAnswer": true
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "idempotent",
    "type": "fill",
    "prompt": "### 冪等律\n請填入單一英文字母：$A+A=\\underline{\\qquad}$。",
    "hint": null,
    "solution": "OR 的冪等律是 $A+A=A$。",
    "rubric": [],
    "correctAnswer": "A",
    "match": "case-insensitive"
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "identity",
    "type": "single",
    "prompt": "### 恆等律\n哪個式子對所有布林值 $A$ 都成立？",
    "hint": null,
    "solution": "$0$ 是 OR 的單位元，因此 $A+0=A$；$1$ 是 AND 的單位元，因此 $A\\cdot1=A$。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$A+0=0$"
      },
      {
        "id": "b",
        "content": "$A+0=A$"
      },
      {
        "id": "c",
        "content": "$A\\cdot1=1$"
      },
      {
        "id": "d",
        "content": "$A\\cdot0=A$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "nand",
    "type": "single",
    "prompt": "### NAND 輸出\n兩輸入 NAND 閘在哪一組輸入時輸出 $0$？",
    "hint": null,
    "solution": "NAND 是 AND 的反相；AND 僅在 $(1,1)$ 輸出 $1$，因此 NAND 僅在這組輸入輸出 $0$。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$(0,0)$"
      },
      {
        "id": "b",
        "content": "$(0,1)$"
      },
      {
        "id": "c",
        "content": "$(1,0)$"
      },
      {
        "id": "d",
        "content": "$(1,1)$"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "xor",
    "type": "multiple",
    "prompt": "### XOR 輸入\n哪些輸入使 $A\\oplus B=1$？",
    "hint": null,
    "solution": "XOR 在兩輸入不同時輸出 $1$，所以選 $(0,1)$ 與 $(1,0)$。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$(0,0)$"
      },
      {
        "id": "b",
        "content": "$(0,1)$"
      },
      {
        "id": "c",
        "content": "$(1,0)$"
      },
      {
        "id": "d",
        "content": "$(1,1)$"
      }
    ],
    "correctOptionIds": [
      "b",
      "c"
    ]
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q1",
    "type": "single",
    "prompt": "### 認識 AND Gate\n下列哪一個是兩個輸入 $A$、$B$ 的 **AND Gate** Boolean expression？",
    "hint": "AND 代表「而且」：兩個輸入都成立時，輸出才成立。",
    "solution": "AND Gate 只有在兩個輸入皆為 $1$ 時輸出 $1$，因此 Boolean expression 為 $Y = AB$。\n\n$$\n1 \\cdot 1 = 1,\\qquad 1 \\cdot 0 = 0\n$$",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$A + B$"
      },
      {
        "id": "b",
        "content": "$AB$"
      },
      {
        "id": "c",
        "content": "$\\overline{A}$"
      },
      {
        "id": "d",
        "content": "$A \\oplus B$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q2",
    "type": "single",
    "prompt": "### 找出方程式的解\n下列哪一組數值是這個方程式的所有實數解？\n\n$$\nx^2 - 5x + 6 = 0\n$$",
    "hint": "尋找兩個相乘為 $6$、相加為 $5$ 的數。",
    "solution": "將左式因式分解：\n\n$$\nx^2 - 5x + 6 = (x-2)(x-3) = 0\n$$\n\n因此 $x=2$ 或 $x=3$。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$x = 1$ 或 $x = 6$"
      },
      {
        "id": "b",
        "content": "$x = 2$ 或 $x = 3$"
      },
      {
        "id": "c",
        "content": "$x = -2$ 或 $x = -3$"
      },
      {
        "id": "d",
        "content": "$x = 0$ 或 $x = 5$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q3",
    "type": "multiple",
    "prompt": "### OR Gate 的輸入組合\n對於 $Y = A + B$ 的 **OR Gate**，哪些輸入組合會使 $Y=1$？請選出所有正確選項。",
    "hint": "只要至少一個輸入為 $1$，OR Gate 就會輸出 $1$。",
    "solution": "正確選項是 **B、C、D**。Boolean algebra 中的 $+$ 代表 OR 運算，因此 $1+1=1$。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "$A=0,\\ B=0$"
      },
      {
        "id": "b",
        "content": "$A=0,\\ B=1$"
      },
      {
        "id": "c",
        "content": "$A=1,\\ B=0$"
      },
      {
        "id": "d",
        "content": "$A=1,\\ B=1$"
      }
    ],
    "correctOptionIds": [
      "b",
      "c",
      "d"
    ]
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q4",
    "type": "true-false",
    "prompt": "### 德摩根定律\n以下等式對所有 Boolean 輸入皆成立。\n\n$$\n\\overline{AB} = \\overline{A} + \\overline{B}\n$$",
    "hint": "把「不是兩者都成立」想成「至少一個不成立」。",
    "solution": "**正確。** 這是德摩根定律。對 AND 的輸出取反，相當於先對兩個輸入取反，再做 OR 運算。",
    "rubric": [],
    "correctAnswer": true
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q5",
    "type": "fill",
    "prompt": "### 寫出邏輯閘名稱\n只有在兩個輸入**不同**時才輸出 $1$ 的邏輯閘，英文縮寫是什麼？\n\n請輸入三個英文字母，不區分大小寫。",
    "hint": "它的完整名稱是 Exclusive OR，符號是 $\\oplus$。",
    "solution": "答案是 **XOR**（互斥或）。當 $A \\ne B$ 時，$A \\oplus B = 1$。",
    "rubric": [],
    "correctAnswer": "XOR",
    "match": "case-insensitive"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q6",
    "type": "calculation",
    "prompt": "### 把解題過程寫下來\n請解出以下方程式，並寫出**完整推導**與代回檢查的過程。\n\n$$\n2x^2 - 7x + 3 = 0\n$$",
    "hint": "試著將左式寫成 $(2x-1)(x-3)$。",
    "solution": "1. 因式分解：$2x^2-7x+3=(2x-1)(x-3)$。\n2. 由零乘積性質，$2x-1=0$ 或 $x-3=0$。\n3. 解得 $x=\\frac{1}{2}$ 或 $x=3$。\n4. 代回確認：\n\n$$\n2(3)^2-7(3)+3=0\n$$\n\n$$\n2\\left(\\frac{1}{2}\\right)^2-7\\left(\\frac{1}{2}\\right)+3=0\n$$",
    "rubric": [
      {
        "score": 2,
        "description": "正確因式分解為 $(2x-1)(x-3)$。"
      },
      {
        "score": 2,
        "description": "寫出兩個根 $x=3$ 與 $x=\\frac{1}{2}$。"
      },
      {
        "score": 2,
        "description": "將兩個根代回原式，確認等式成立。"
      }
    ],
    "referenceAnswer": "$x=3$ 或 $x=\\frac{1}{2}$。"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q7",
    "type": "drawing",
    "prompt": "### 畫出你的邏輯\n畫出具有兩個輸入 **A、B** 與一個輸出 **Y** 的 **AND Gate** 示意圖。\n\n標示輸入、輸出與邏輯閘的外形，並註記 $Y=AB$。",
    "hint": "先畫 D 形閘體，再加上左邊兩條線與右邊一條線。",
    "solution": "確認圖中具有：\n\n- 左側兩個獨立輸入 A、B。\n- AND Gate 的 D 形外框（輸出端沒有反相小圓圈）。\n- 右側一個輸出 Y。\n- 與圖一致的 Boolean expression：$Y=AB$。",
    "rubric": [
      {
        "score": 1,
        "description": "正確畫出 AND Gate 的 D 形外框。"
      },
      {
        "score": 1,
        "description": "正確標示兩個輸入 A、B。"
      },
      {
        "score": 1,
        "description": "正確標示輸出 Y。"
      },
      {
        "score": 1,
        "description": "正確註記 $Y=AB$。"
      }
    ],
    "referenceAnswer": "AND Gate 的左側為一直線，右側為半圓，整體呈 **D 形**。左側接兩條輸入線，分別標示 **A** 與 **B**；右側接一條輸出線，標示 **Y**，並寫上 $Y=AB$。"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "composition",
    "type": "fill",
    "prompt": "### 關係合成\n若 $R=\\{(1,2)\\}$、$S=\\{(2,3)\\}$，請以 `(1,3)` 格式填出 $S\\circ R$ 唯一的有序對。",
    "hint": null,
    "solution": "先經 $R$ 從 $1$ 到 $2$，再經 $S$ 從 $2$ 到 $3$，所以 $S\\circ R=\\{(1,3)\\}$。",
    "rubric": [],
    "correctAnswer": "(1,3)",
    "match": "exact"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "empty-symmetric",
    "type": "true-false",
    "prompt": "### 空關係\n非空集合上的空關係 $\\varnothing$ 是對稱的。",
    "hint": null,
    "solution": "空關係沒有任何 $(a,b)$ 需要檢查，所以對稱條件真空成立。",
    "rubric": [],
    "correctAnswer": true
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "equivalence",
    "type": "fill",
    "prompt": "### 等價關係\n等價關係須自反、傳遞，還須具備哪一種性質？請填「對稱」。",
    "hint": null,
    "solution": "等價關係同時具有自反、對稱、傳遞三種性質。",
    "rubric": [],
    "correctAnswer": "對稱",
    "match": "exact"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "partial-order",
    "type": "multiple",
    "prompt": "### 偏序條件\n偏序關係必須具備哪些性質？",
    "hint": null,
    "solution": "偏序的定義是自反、反對稱、傳遞；不要求對稱。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "自反"
      },
      {
        "id": "b",
        "content": "對稱"
      },
      {
        "id": "c",
        "content": "反對稱"
      },
      {
        "id": "d",
        "content": "傳遞"
      }
    ],
    "correctOptionIds": [
      "a",
      "c",
      "d"
    ]
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "reflexive",
    "type": "single",
    "prompt": "### 自反關係\n在 $X=\\{1,2\\}$ 上，$R=\\{(1,1),(2,2)\\}$ 是否自反？",
    "hint": null,
    "solution": "自反只要求 $(1,1)$ 和 $(2,2)$ 都在 $R$ 中；此關係符合。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "是，因為 $X$ 中每個元素都與自己有關係。"
      },
      {
        "id": "b",
        "content": "否，因為缺少 $(1,2)$。"
      },
      {
        "id": "c",
        "content": "否，因為缺少 $(2,1)$。"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "symmetry",
    "type": "true-false",
    "prompt": "### 對稱的定義\n若 $R$ 對稱，則對任意 $a,b$，只要 $(a,b)\\in R$，就有 $(b,a)\\in R$。",
    "hint": null,
    "solution": "這正是對稱關係的定義。",
    "rubric": [],
    "correctAnswer": true
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "transitivity",
    "type": "single",
    "prompt": "### 檢查傳遞性\n在 $X=\\{1,2,3\\}$ 上，$R=\\{(1,2),(2,3)\\}$ 是否傳遞？",
    "hint": null,
    "solution": "由 $(1,2)$ 與 $(2,3)$，傳遞性要求 $(1,3)$ 也在 $R$ 中；它並不存在。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "是，因為關係中只有兩個有序對。"
      },
      {
        "id": "b",
        "content": "否，因為缺少 $(1,3)$。"
      },
      {
        "id": "c",
        "content": "否，因為缺少 $(3,1)$。"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "universal",
    "type": "multiple",
    "prompt": "### 全關係\n在 $X=\\{1,2\\}$ 上，$R=X\\times X$ 具有哪些性質？",
    "hint": null,
    "solution": "所有有序對都在 $R$ 中，因此自反、對稱且傳遞；它包含 $(1,1)$ 與 $(2,2)$，所以不反自反。",
    "rubric": [],
    "options": [
      {
        "id": "a",
        "content": "自反"
      },
      {
        "id": "b",
        "content": "對稱"
      },
      {
        "id": "c",
        "content": "傳遞"
      },
      {
        "id": "d",
        "content": "反自反"
      }
    ],
    "correctOptionIds": [
      "a",
      "b",
      "c"
    ]
  }
] as const
