// Generated by scripts/generate-ai-quiz-context.mjs from canonical Quiz Markdown. Do not edit.
export const AI_QUIZ_CONTEXT = [
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "absorption",
    "questionIndex": 2,
    "type": "true-false",
    "prompt": "### 吸收律\n$A+AB=A$ 對所有布林值 $A,B$ 都成立。",
    "hint": null,
    "solution": "$A+AB=A(1+B)=A\\cdot1=A$。",
    "rubric": [],
    "points": 1,
    "correctAnswer": true
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "demorgan",
    "questionIndex": 1,
    "type": "multiple",
    "prompt": "### 選出所有恆等式\n以下哪些式子對所有 $A,B$ 都成立？",
    "hint": null,
    "solution": "前兩式是德摩根定律；第三式是互補律。$A\\overline A$ 永遠等於 $0$。",
    "rubric": [],
    "points": 3,
    "options": [
      {
        "id": "a",
        "content": "$\\overline{A+B}=\\overline A\\,\\overline B$"
      },
      {
        "id": "b",
        "content": "$\\overline{AB}=\\overline A+\\overline B$"
      },
      {
        "id": "c",
        "content": "$A+\\overline A=1$"
      },
      {
        "id": "d",
        "content": "$A\\overline A=1$"
      }
    ],
    "correctOptionIds": [
      "a",
      "b",
      "c"
    ]
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "double-negation",
    "questionIndex": 6,
    "type": "true-false",
    "prompt": "### 雙重否定\n$\\overline{\\overline A}=A$。",
    "hint": null,
    "solution": "對布林值取反兩次會得到原值。",
    "rubric": [],
    "points": 1,
    "correctAnswer": true
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "idempotent",
    "questionIndex": 3,
    "type": "fill",
    "prompt": "### 冪等律\n請填入單一英文字母：$A+A=\\underline{\\qquad}$。",
    "hint": null,
    "solution": "OR 的冪等律是 $A+A=A$。",
    "rubric": [],
    "points": 2,
    "correctAnswer": "A",
    "match": "case-insensitive"
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "identity",
    "questionIndex": 0,
    "type": "single",
    "prompt": "### 恆等律\n哪個式子對所有布林值 $A$ 都成立？",
    "hint": null,
    "solution": "$0$ 是 OR 的單位元，因此 $A+0=A$；$1$ 是 AND 的單位元，因此 $A\\cdot1=A$。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$A+0=0$"
      },
      {
        "id": "b",
        "content": "$A+0=A$"
      },
      {
        "id": "c",
        "content": "$A\\cdot1=1$"
      },
      {
        "id": "d",
        "content": "$A\\cdot0=A$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "nand",
    "questionIndex": 4,
    "type": "single",
    "prompt": "### NAND 輸出\n兩輸入 NAND 閘在哪一組輸入時輸出 $0$？",
    "hint": null,
    "solution": "NAND 是 AND 的反相；AND 僅在 $(1,1)$ 輸出 $1$，因此 NAND 僅在這組輸入輸出 $0$。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$(0,0)$"
      },
      {
        "id": "b",
        "content": "$(0,1)$"
      },
      {
        "id": "c",
        "content": "$(1,0)$"
      },
      {
        "id": "d",
        "content": "$(1,1)$"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "quizId": "boolean-algebra",
    "revision": "1",
    "questionId": "xor",
    "questionIndex": 5,
    "type": "multiple",
    "prompt": "### XOR 輸入\n哪些輸入使 $A\\oplus B=1$？",
    "hint": null,
    "solution": "XOR 在兩輸入不同時輸出 $1$，所以選 $(0,1)$ 與 $(1,0)$。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$(0,0)$"
      },
      {
        "id": "b",
        "content": "$(0,1)$"
      },
      {
        "id": "c",
        "content": "$(1,0)$"
      },
      {
        "id": "d",
        "content": "$(1,1)$"
      }
    ],
    "correctOptionIds": [
      "b",
      "c"
    ]
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q1",
    "questionIndex": 0,
    "type": "single",
    "prompt": "### 認識 AND Gate\n下列哪一個是兩個輸入 $A$、$B$ 的 **AND Gate** Boolean expression？",
    "hint": "AND 代表「而且」：兩個輸入都成立時，輸出才成立。",
    "solution": "AND Gate 只有在兩個輸入皆為 $1$ 時輸出 $1$，因此 Boolean expression 為 $Y = AB$。\n\n$$\n1 \\cdot 1 = 1,\\qquad 1 \\cdot 0 = 0\n$$",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$A + B$"
      },
      {
        "id": "b",
        "content": "$AB$"
      },
      {
        "id": "c",
        "content": "$\\overline{A}$"
      },
      {
        "id": "d",
        "content": "$A \\oplus B$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q2",
    "questionIndex": 1,
    "type": "single",
    "prompt": "### 找出方程式的解\n下列哪一組數值是這個方程式的所有實數解？\n\n$$\nx^2 - 5x + 6 = 0\n$$",
    "hint": "尋找兩個相乘為 $6$、相加為 $5$ 的數。",
    "solution": "將左式因式分解：\n\n$$\nx^2 - 5x + 6 = (x-2)(x-3) = 0\n$$\n\n因此 $x=2$ 或 $x=3$。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$x = 1$ 或 $x = 6$"
      },
      {
        "id": "b",
        "content": "$x = 2$ 或 $x = 3$"
      },
      {
        "id": "c",
        "content": "$x = -2$ 或 $x = -3$"
      },
      {
        "id": "d",
        "content": "$x = 0$ 或 $x = 5$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q3",
    "questionIndex": 2,
    "type": "multiple",
    "prompt": "### OR Gate 的輸入組合\n對於 $Y = A + B$ 的 **OR Gate**，哪些輸入組合會使 $Y=1$？請選出所有正確選項。",
    "hint": "只要至少一個輸入為 $1$，OR Gate 就會輸出 $1$。",
    "solution": "正確選項是 **B、C、D**。Boolean algebra 中的 $+$ 代表 OR 運算，因此 $1+1=1$。",
    "rubric": [],
    "points": 3,
    "options": [
      {
        "id": "a",
        "content": "$A=0,\\ B=0$"
      },
      {
        "id": "b",
        "content": "$A=0,\\ B=1$"
      },
      {
        "id": "c",
        "content": "$A=1,\\ B=0$"
      },
      {
        "id": "d",
        "content": "$A=1,\\ B=1$"
      }
    ],
    "correctOptionIds": [
      "b",
      "c",
      "d"
    ]
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q4",
    "questionIndex": 3,
    "type": "true-false",
    "prompt": "### 德摩根定律\n以下等式對所有 Boolean 輸入皆成立。\n\n$$\n\\overline{AB} = \\overline{A} + \\overline{B}\n$$",
    "hint": "把「不是兩者都成立」想成「至少一個不成立」。",
    "solution": "**正確。** 這是德摩根定律。對 AND 的輸出取反，相當於先對兩個輸入取反，再做 OR 運算。",
    "rubric": [],
    "points": 1,
    "correctAnswer": true
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q5",
    "questionIndex": 4,
    "type": "fill",
    "prompt": "### 寫出邏輯閘名稱\n只有在兩個輸入**不同**時才輸出 $1$ 的邏輯閘，英文縮寫是什麼？\n\n請輸入三個英文字母，不區分大小寫。",
    "hint": "它的完整名稱是 Exclusive OR，符號是 $\\oplus$。",
    "solution": "答案是 **XOR**（互斥或）。當 $A \\ne B$ 時，$A \\oplus B = 1$。",
    "rubric": [],
    "points": 2,
    "correctAnswer": "XOR",
    "match": "case-insensitive"
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q6",
    "questionIndex": 5,
    "type": "calculation",
    "prompt": "### 把解題過程寫下來\n請解出以下方程式，並寫出**完整推導**與代回檢查的過程。\n\n$$\n2x^2 - 7x + 3 = 0\n$$",
    "hint": "試著將左式寫成 $(2x-1)(x-3)$。",
    "solution": "1. 因式分解：$2x^2-7x+3=(2x-1)(x-3)$。\n2. 由零乘積性質，$2x-1=0$ 或 $x-3=0$。\n3. 解得 $x=\\frac{1}{2}$ 或 $x=3$。\n4. 代回確認：\n\n$$\n2(3)^2-7(3)+3=0\n$$\n\n$$\n2\\left(\\frac{1}{2}\\right)^2-7\\left(\\frac{1}{2}\\right)+3=0\n$$",
    "rubric": [
      {
        "score": 2,
        "description": "正確因式分解為 $(2x-1)(x-3)$。"
      },
      {
        "score": 2,
        "description": "寫出兩個根 $x=3$ 與 $x=\\frac{1}{2}$。"
      },
      {
        "score": 2,
        "description": "將兩個根代回原式，確認等式成立。"
      }
    ],
    "points": 6,
    "referenceAnswer": "$x=3$ 或 $x=\\frac{1}{2}$。",
    "gradingRubric": [
      {
        "id": "r1",
        "points": 2,
        "description": "正確因式分解為 $(2x-1)(x-3)$。"
      },
      {
        "id": "r2",
        "points": 2,
        "description": "寫出兩個根 $x=3$ 與 $x=\\frac{1}{2}$。"
      },
      {
        "id": "r3",
        "points": 2,
        "description": "將兩個根代回原式，確認等式成立。"
      }
    ]
  },
  {
    "quizId": "demo",
    "revision": "v1-7d7c900e",
    "questionId": "q7",
    "questionIndex": 6,
    "type": "drawing",
    "prompt": "### 畫出你的邏輯\n畫出具有兩個輸入 **A、B** 與一個輸出 **Y** 的 **AND Gate** 示意圖。\n\n標示輸入、輸出與邏輯閘的外形，並註記 $Y=AB$。",
    "hint": "先畫 D 形閘體，再加上左邊兩條線與右邊一條線。",
    "solution": "確認圖中具有：\n\n- 左側兩個獨立輸入 A、B。\n- AND Gate 的 D 形外框（輸出端沒有反相小圓圈）。\n- 右側一個輸出 Y。\n- 與圖一致的 Boolean expression：$Y=AB$。",
    "rubric": [
      {
        "score": 1,
        "description": "正確畫出 AND Gate 的 D 形外框。"
      },
      {
        "score": 1,
        "description": "正確標示兩個輸入 A、B。"
      },
      {
        "score": 1,
        "description": "正確標示輸出 Y。"
      },
      {
        "score": 1,
        "description": "正確註記 $Y=AB$。"
      }
    ],
    "points": 4,
    "referenceAnswer": "AND Gate 的左側為一直線，右側為半圓，整體呈 **D 形**。左側接兩條輸入線，分別標示 **A** 與 **B**；右側接一條輸出線，標示 **Y**，並寫上 $Y=AB$。",
    "drawing": {
      "width": 800,
      "height": 600
    },
    "gradingRubric": [
      {
        "id": "r1",
        "points": 1,
        "description": "正確畫出 AND Gate 的 D 形外框。"
      },
      {
        "id": "r2",
        "points": 1,
        "description": "正確標示兩個輸入 A、B。"
      },
      {
        "id": "r3",
        "points": 1,
        "description": "正確標示輸出 Y。"
      },
      {
        "id": "r4",
        "points": 1,
        "description": "正確註記 $Y=AB$。"
      }
    ]
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q1",
    "questionIndex": 0,
    "type": "single",
    "prompt": "### 認識 AND Gate\n下列哪一個是兩個輸入 $A$、$B$ 的 **AND Gate** Boolean expression？",
    "hint": "AND 代表「而且」：兩個輸入都成立時，輸出才成立。",
    "solution": "AND Gate 只有在兩個輸入皆為 $1$ 時輸出 $1$，因此 Boolean expression 為 $Y = AB$。\n\n$$\n1 \\cdot 1 = 1,\\qquad 1 \\cdot 0 = 0\n$$",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$A + B$"
      },
      {
        "id": "b",
        "content": "$AB$"
      },
      {
        "id": "c",
        "content": "$\\overline{A}$"
      },
      {
        "id": "d",
        "content": "$A \\oplus B$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q2",
    "questionIndex": 1,
    "type": "single",
    "prompt": "### 找出方程式的解\n下列哪一組數值是這個方程式的所有實數解？\n\n$$\nx^2 - 5x + 6 = 0\n$$",
    "hint": "尋找兩個相乘為 $6$、相加為 $5$ 的數。",
    "solution": "將左式因式分解：\n\n$$\nx^2 - 5x + 6 = (x-2)(x-3) = 0\n$$\n\n因此 $x=2$ 或 $x=3$。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "$x = 1$ 或 $x = 6$"
      },
      {
        "id": "b",
        "content": "$x = 2$ 或 $x = 3$"
      },
      {
        "id": "c",
        "content": "$x = -2$ 或 $x = -3$"
      },
      {
        "id": "d",
        "content": "$x = 0$ 或 $x = 5$"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q3",
    "questionIndex": 2,
    "type": "multiple",
    "prompt": "### OR Gate 的輸入組合\n對於 $Y = A + B$ 的 **OR Gate**，哪些輸入組合會使 $Y=1$？請選出所有正確選項。",
    "hint": "只要至少一個輸入為 $1$，OR Gate 就會輸出 $1$。",
    "solution": "正確選項是 **B、C、D**。Boolean algebra 中的 $+$ 代表 OR 運算，因此 $1+1=1$。",
    "rubric": [],
    "points": 3,
    "options": [
      {
        "id": "a",
        "content": "$A=0,\\ B=0$"
      },
      {
        "id": "b",
        "content": "$A=0,\\ B=1$"
      },
      {
        "id": "c",
        "content": "$A=1,\\ B=0$"
      },
      {
        "id": "d",
        "content": "$A=1,\\ B=1$"
      }
    ],
    "correctOptionIds": [
      "b",
      "c",
      "d"
    ]
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q4",
    "questionIndex": 3,
    "type": "true-false",
    "prompt": "### 德摩根定律\n以下等式對所有 Boolean 輸入皆成立。\n\n$$\n\\overline{AB} = \\overline{A} + \\overline{B}\n$$",
    "hint": "把「不是兩者都成立」想成「至少一個不成立」。",
    "solution": "**正確。** 這是德摩根定律。對 AND 的輸出取反，相當於先對兩個輸入取反，再做 OR 運算。",
    "rubric": [],
    "points": 1,
    "correctAnswer": true
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q5",
    "questionIndex": 4,
    "type": "fill",
    "prompt": "### 寫出邏輯閘名稱\n只有在兩個輸入**不同**時才輸出 $1$ 的邏輯閘，英文縮寫是什麼？\n\n請輸入三個英文字母，不區分大小寫。",
    "hint": "它的完整名稱是 Exclusive OR，符號是 $\\oplus$。",
    "solution": "答案是 **XOR**（互斥或）。當 $A \\ne B$ 時，$A \\oplus B = 1$。",
    "rubric": [],
    "points": 2,
    "correctAnswer": "XOR",
    "match": "case-insensitive"
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q6",
    "questionIndex": 5,
    "type": "calculation",
    "prompt": "### 把解題過程寫下來\n請解出以下方程式，並寫出**完整推導**與代回檢查的過程。\n\n$$\n2x^2 - 7x + 3 = 0\n$$",
    "hint": "試著將左式寫成 $(2x-1)(x-3)$。",
    "solution": "1. 因式分解：$2x^2-7x+3=(2x-1)(x-3)$。\n2. 由零乘積性質，$2x-1=0$ 或 $x-3=0$。\n3. 解得 $x=\\frac{1}{2}$ 或 $x=3$。\n4. 代回確認：\n\n$$\n2(3)^2-7(3)+3=0\n$$\n\n$$\n2\\left(\\frac{1}{2}\\right)^2-7\\left(\\frac{1}{2}\\right)+3=0\n$$",
    "rubric": [
      {
        "score": 2,
        "description": "正確因式分解為 $(2x-1)(x-3)$。"
      },
      {
        "score": 2,
        "description": "寫出兩個根 $x=3$ 與 $x=\\frac{1}{2}$。"
      },
      {
        "score": 2,
        "description": "將兩個根代回原式，確認等式成立。"
      }
    ],
    "points": 6,
    "referenceAnswer": "$x=3$ 或 $x=\\frac{1}{2}$。",
    "drawing": {
      "width": 800,
      "height": 600
    },
    "gradingRubric": [
      {
        "id": "r1",
        "points": 2,
        "description": "正確因式分解為 $(2x-1)(x-3)$。"
      },
      {
        "id": "r2",
        "points": 2,
        "description": "寫出兩個根 $x=3$ 與 $x=\\frac{1}{2}$。"
      },
      {
        "id": "r3",
        "points": 2,
        "description": "將兩個根代回原式，確認等式成立。"
      }
    ]
  },
  {
    "quizId": "demo",
    "revision": "v2-handwriting",
    "questionId": "q7",
    "questionIndex": 6,
    "type": "drawing",
    "prompt": "### 畫出你的邏輯\n畫出具有兩個輸入 **A、B** 與一個輸出 **Y** 的 **AND Gate** 示意圖。\n\n標示輸入、輸出與邏輯閘的外形，並註記 $Y=AB$。",
    "hint": "先畫 D 形閘體，再加上左邊兩條線與右邊一條線。",
    "solution": "確認圖中具有：\n\n- 左側兩個獨立輸入 A、B。\n- AND Gate 的 D 形外框（輸出端沒有反相小圓圈）。\n- 右側一個輸出 Y。\n- 與圖一致的 Boolean expression：$Y=AB$。",
    "rubric": [
      {
        "score": 1,
        "description": "正確畫出 AND Gate 的 D 形外框。"
      },
      {
        "score": 1,
        "description": "正確標示兩個輸入 A、B。"
      },
      {
        "score": 1,
        "description": "正確標示輸出 Y。"
      },
      {
        "score": 1,
        "description": "正確註記 $Y=AB$。"
      }
    ],
    "points": 4,
    "referenceAnswer": "AND Gate 的左側為一直線，右側為半圓，整體呈 **D 形**。左側接兩條輸入線，分別標示 **A** 與 **B**；右側接一條輸出線，標示 **Y**，並寫上 $Y=AB$。",
    "drawing": {
      "width": 800,
      "height": 600
    },
    "gradingRubric": [
      {
        "id": "r1",
        "points": 1,
        "description": "正確畫出 AND Gate 的 D 形外框。"
      },
      {
        "id": "r2",
        "points": 1,
        "description": "正確標示兩個輸入 A、B。"
      },
      {
        "id": "r3",
        "points": 1,
        "description": "正確標示輸出 Y。"
      },
      {
        "id": "r4",
        "points": 1,
        "description": "正確註記 $Y=AB$。"
      }
    ]
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q1-i",
    "questionIndex": 0,
    "type": "single",
    "prompt": "### 1. (I)\n在 COMPUTER 這個字中，若僅拿 5 個字母排列，不允許字母重複，則（大小為 5）的排列數為",
    "hint": null,
    "solution": "COMPUTER 的 $C,O,M,P,U,T,E,R$ 共 8 個字母皆不相同。依序選出 5 個不同字母，共有 $8\\cdot7\\cdot6\\cdot5\\cdot4=8!/3!=6720$ 種，因此選 (c)。亦可先選字母再排列：$\\binom{8}{5}5!=6720$。",
    "rubric": [],
    "points": 6,
    "options": [
      {
        "id": "a",
        "content": "$8!$"
      },
      {
        "id": "b",
        "content": "$5!$"
      },
      {
        "id": "c",
        "content": "$8!/3!$"
      },
      {
        "id": "d",
        "content": "$8!/(3!5!)$"
      },
      {
        "id": "e",
        "content": "$8^5$"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q1-ii",
    "questionIndex": 1,
    "type": "single",
    "prompt": "### 1. (II)\n將 5 個不同物體分配至 3 個相同容器且無容器是空的方法數 = ?",
    "hint": null,
    "solution": "相同容器對應沒有標號的三個非空組。組大小只能為 $(3,1,1)$ 或 $(2,2,1)$：前者有 $\\binom{5}{3}=10$ 種，後者先選單獨物體，再把其餘四個分成兩對，有 $5\\binom{4}{2}/2=15$ 種。因此共 $10+15=25$ 種，選 (a)。用容斥驗算：$S(5,3)=(3^5-3\\cdot2^5+3\\cdot1^5)/3!=25$。",
    "rubric": [],
    "points": 6,
    "options": [
      {
        "id": "a",
        "content": "25"
      },
      {
        "id": "b",
        "content": "21"
      },
      {
        "id": "c",
        "content": "18"
      },
      {
        "id": "d",
        "content": "16"
      },
      {
        "id": "e",
        "content": "15"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q1-iii",
    "questionIndex": 2,
    "type": "single",
    "prompt": "### 1. (III)\n$(x+y)^7$ 展開後 $x^5y^2$ 的係數等於",
    "hint": null,
    "solution": "二項式定理給出 $(x+y)^7=\\sum_{k=0}^{7}\\binom{7}{k}x^{7-k}y^k$。$x^5y^2$ 對應 $k=2$，係數為 $\\binom{7}{2}=21$，選 (b)。也就是在七個因式中選兩個提供 $y$。",
    "rubric": [],
    "points": 6,
    "options": [
      {
        "id": "a",
        "content": "30"
      },
      {
        "id": "b",
        "content": "21"
      },
      {
        "id": "c",
        "content": "15"
      },
      {
        "id": "d",
        "content": "12"
      },
      {
        "id": "e",
        "content": "10"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q1-iv",
    "questionIndex": 3,
    "type": "single",
    "prompt": "### 1. (IV)\n函數 $f:\\mathbb{R}\\to\\mathbb{R}$，$f(x)=x^2$",
    "hint": null,
    "solution": "原試卷選項中的 $R$ 依題幹指函數 $f$，此處保留原選項文字。因 $f(1)=f(-1)=1$ 且 $1\\ne-1$，$f$ 不是一對一函數。對每個實數 $x$，$x^2\\ge0$，所以陪域中的 $-1$ 沒有原像，$f$ 也不是映成函數。因此選 (d)。",
    "rubric": [],
    "points": 6,
    "options": [
      {
        "id": "a",
        "content": "$R$ 是一對一函數且是映成函數"
      },
      {
        "id": "b",
        "content": "$R$ 不是一對一函數且 $R$ 是映成函數"
      },
      {
        "id": "c",
        "content": "$R$ 是一對一函數且 $R$ 不是映成函數"
      },
      {
        "id": "d",
        "content": "$R$ 不是一對一函數且 $R$ 不是映成函數"
      }
    ],
    "correctOptionId": "d"
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q1-v",
    "questionIndex": 4,
    "type": "single",
    "prompt": "### 1. (V)\nHow many integers between 1 and 1000 are not divisible by 2, 5, or 17?",
    "hint": null,
    "solution": "在 $1,2,\\ldots,1000$ 中，2、5、17 的倍數分別有 $500,200,58$ 個。兩兩交集是 10、34、85 的倍數，分別有 $100,29,11$ 個；三者交集是 170 的倍數，有 $5$ 個。由容斥原理，不被三者中任何一個整除的個數為\n\n$$\n1000-(500+200+58)+(100+29+11)-5=377.\n$$\n\n因此選 (b)。",
    "rubric": [],
    "points": 6,
    "options": [
      {
        "id": "a",
        "content": "376"
      },
      {
        "id": "b",
        "content": "377"
      },
      {
        "id": "c",
        "content": "378"
      },
      {
        "id": "d",
        "content": "379"
      },
      {
        "id": "e",
        "content": "380"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q1-vi",
    "questionIndex": 5,
    "type": "single",
    "prompt": "### 1. (VI)\n$A=\\{1,2,3\\}$，$A$ 上的關係 $R=\\{(1,1),(2,2),(3,3),(1,2),(2,1)\\}$",
    "hint": null,
    "solution": "三個對角有序對皆在 $R$ 中，故自反；$(1,2)$ 與 $(2,1)$ 同時存在，故對稱。關係恰為 $\\{1,2\\}\\times\\{1,2\\}$ 與 $\\{3\\}\\times\\{3\\}$ 的聯集；若 $aRb$ 且 $bRc$，三者必在同一組，故 $aRc$，因此傳遞。它是等價關係。但 $1R2$、$2R1$ 且 $1\\ne2$，不符合反對稱性，所以不是偏序關係，選 (c)。",
    "rubric": [],
    "points": 6,
    "options": [
      {
        "id": "a",
        "content": "$R$ 是等價關係且是偏序關係"
      },
      {
        "id": "b",
        "content": "$R$ 不是等價關係且 $R$ 是偏序關係"
      },
      {
        "id": "c",
        "content": "$R$ 是等價關係且 $R$ 不是偏序關係"
      },
      {
        "id": "d",
        "content": "$R$ 不是等價關係且 $R$ 不是偏序關係"
      }
    ],
    "correctOptionId": "c"
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q2",
    "questionIndex": 6,
    "type": "calculation",
    "prompt": "### 2.（12 分）\nHow many arrangements of the letters in MISSISSIPPI have no consecutive S’s ?\n\n請寫計算過程或說明理由。",
    "hint": null,
    "solution": "MISSISSIPPI 有 $M$ 1 個、$I$ 4 個、$S$ 4 個、$P$ 2 個，共 11 個字母。\n\n先排列七個非 $S$ 字母 $M,I,I,I,I,P,P$。扣除相同 $I$ 與相同 $P$ 的重複計數，排列數為\n\n$$\n\\frac{7!}{4!2!}=105.\n$$\n\n對任何固定的非 $S$ 排列，七個字母之間有六個空隙，加上左右兩端共八個空隙。為了讓四個 $S$ 互不相鄰，每個空隙至多放一個 $S$；從八個空隙選出四個，共有\n\n$$\n\\binom{8}{4}=70\n$$\n\n種選法。四個 $S$ 相同，不再乘上 $4!$。所選空隙之間都有非 $S$ 字母隔開，故不會出現連續的 $S$。\n\n反過來，從任何符合條件的排列刪去四個 $S$，便唯一得到非 $S$ 排列及四個所選空隙。因此上述計數既無重複也無遺漏，答案為\n\n$$\n\\frac{7!}{4!2!}\\binom{8}{4}=105\\cdot70=7350.\n$$",
    "rubric": [
      {
        "score": 3,
        "description": "正確辨認 $M$ 1 個、$I$ 4 個、$S$ 4 個、$P$ 2 個，並算出非 $S$ 字母排列數 $7!/(4!2!)=105$。"
      },
      {
        "score": 3,
        "description": "說明七個非 $S$ 字母形成八個空隙，每個空隙至多放一個 $S$，故有 $\\binom{8}{4}=70$ 種選法。"
      },
      {
        "score": 3,
        "description": "說明四個 $S$ 相同，不乘 $4!$，且每個有效排列唯一對應一個非 $S$ 排列與四個空隙，保證沒有連續 $S$、重複或遺漏。"
      },
      {
        "score": 3,
        "description": "正確相乘得到 $105\\cdot70=7350$，或以同樣完整且正確的方法得到此結果。"
      }
    ],
    "points": 12,
    "referenceAnswer": "$7350$ 種。",
    "gradingRubric": [
      {
        "id": "r1",
        "points": 3,
        "description": "正確辨認 $M$ 1 個、$I$ 4 個、$S$ 4 個、$P$ 2 個，並算出非 $S$ 字母排列數 $7!/(4!2!)=105$。"
      },
      {
        "id": "r2",
        "points": 3,
        "description": "說明七個非 $S$ 字母形成八個空隙，每個空隙至多放一個 $S$，故有 $\\binom{8}{4}=70$ 種選法。"
      },
      {
        "id": "r3",
        "points": 3,
        "description": "說明四個 $S$ 相同，不乘 $4!$，且每個有效排列唯一對應一個非 $S$ 排列與四個空隙，保證沒有連續 $S$、重複或遺漏。"
      },
      {
        "id": "r4",
        "points": 3,
        "description": "正確相乘得到 $105\\cdot70=7350$，或以同樣完整且正確的方法得到此結果。"
      }
    ]
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q3",
    "questionIndex": 7,
    "type": "calculation",
    "prompt": "### 3.（14 分）\n(a) 有多少種方法可分配 10 個（相同）白彈珠至 6 個相異容器？\n\n(b) Determine the number of integer solutions of\n\n$$\nx_1+x_2+x_3+x_4=32,\n$$\n\nwhere $x_1\\ge5$, $x_2\\ge5$, $x_3\\ge7$, $x_4\\ge7$.\n\n請寫計算過程或說明理由。",
    "hint": null,
    "solution": "**(a)** 原文沒有要求每個容器非空，因此允許空容器。令第 $j$ 個容器有 $y_j$ 顆彈珠，則\n\n$$\ny_1+y_2+y_3+y_4+y_5+y_6=10,\\qquad y_j\\ge0.\n$$\n\n彈珠相同而六個容器相異，所以以十個星號與五個隔板表示分配；相鄰隔板或端點的隔板表示空容器。共有十五個位置，選五個放隔板，得\n\n$$\n\\binom{10+6-1}{6-1}=\\binom{15}{5}\n=\\frac{15\\cdot14\\cdot13\\cdot12\\cdot11}{5\\cdot4\\cdot3\\cdot2\\cdot1}\n=3003.\n$$\n\n**(b)** 原試卷的四個下界為 $\\ge$。令\n\n$$\ny_1=x_1-5,\\quad y_2=x_2-5,\\quad y_3=x_3-7,\\quad y_4=x_4-7.\n$$\n\n這建立原題整數解與下列非負整數解的一一對應：\n\n$$\ny_1+y_2+y_3+y_4=32-(5+5+7+7)=8,\\qquad y_i\\ge0.\n$$\n\n用八個星號與三個隔板，解的個數為\n\n$$\n\\binom{8+4-1}{4-1}=\\binom{11}{3}\n=\\frac{11\\cdot10\\cdot9}{3\\cdot2\\cdot1}=165.\n$$",
    "rubric": [
      {
        "score": 2,
        "description": "(a) 明確採用允許空容器的解讀，以六個非負整數表示相異容器的彈珠數，且總和為 10。"
      },
      {
        "score": 3,
        "description": "(a) 正確使用十個星號、五個隔板的計數，得到 $\\binom{15}{5}$ 或等價的完整推導。"
      },
      {
        "score": 2,
        "description": "(a) 正確算出 $3003$ 種分配。"
      },
      {
        "score": 3,
        "description": "(b) 依原試卷的 $\\ge$ 下界，正確令 $y_1=x_1-5$、$y_2=x_2-5$、$y_3=x_3-7$、$y_4=x_4-7$，得到四個非負整數總和為 8。"
      },
      {
        "score": 2,
        "description": "(b) 正確使用星與棒，得到 $\\binom{11}{3}$ 或等價的完整推導。"
      },
      {
        "score": 2,
        "description": "(b) 正確算出 $165$ 個整數解。"
      }
    ],
    "points": 14,
    "referenceAnswer": "(a) $\\binom{15}{5}=3003$ 種（允許空容器）。\n\n(b) $\\binom{11}{3}=165$ 個整數解。",
    "gradingRubric": [
      {
        "id": "r1",
        "points": 2,
        "description": "(a) 明確採用允許空容器的解讀，以六個非負整數表示相異容器的彈珠數，且總和為 10。"
      },
      {
        "id": "r2",
        "points": 3,
        "description": "(a) 正確使用十個星號、五個隔板的計數，得到 $\\binom{15}{5}$ 或等價的完整推導。"
      },
      {
        "id": "r3",
        "points": 2,
        "description": "(a) 正確算出 $3003$ 種分配。"
      },
      {
        "id": "r4",
        "points": 3,
        "description": "(b) 依原試卷的 $\\ge$ 下界，正確令 $y_1=x_1-5$、$y_2=x_2-5$、$y_3=x_3-7$、$y_4=x_4-7$，得到四個非負整數總和為 8。"
      },
      {
        "id": "r5",
        "points": 2,
        "description": "(b) 正確使用星與棒，得到 $\\binom{11}{3}$ 或等價的完整推導。"
      },
      {
        "id": "r6",
        "points": 2,
        "description": "(b) 正確算出 $165$ 個整數解。"
      }
    ]
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q4",
    "questionIndex": 8,
    "type": "calculation",
    "prompt": "### 4.（12 分）\nFor the following relation $R$, determine whether the relation is reflexive, symmetric, antisymmetric, or transitive?\n\n$R$ is the relation on $\\mathbb{Z}^{+}$ where $aRb$ if $a\\mid b$（$a\\mid b$ 意即 $a$ 整除 $b$）。\n\n請寫計算過程或說明理由。",
    "hint": null,
    "solution": "逐一檢查四個性質，所有元素皆為正整數。\n\n1. **Reflexive（自反）：是。** 對任意正整數 $a$，$a=a\\cdot1$，所以 $a\\mid a$，即 $aRa$。\n2. **Symmetric（對稱）：否。** $2\\mid4$，但 $4\\nmid2$；故 $2R4$ 不推出 $4R2$，這是反例。\n3. **Antisymmetric（反對稱）：是。** 假設 $a\\mid b$ 且 $b\\mid a$，則存在正整數 $m,n$ 使 $b=ma$、$a=nb$。代入得到 $a=nma$。因 $a>0$，可除以 $a$ 得 $mn=1$，因此 $m=n=1$，所以 $a=b$。\n4. **Transitive（傳遞）：是。** 假設 $a\\mid b$ 且 $b\\mid c$，則存在正整數 $m,n$ 使 $b=ma$、$c=nb$。於是 $c=nma$，所以 $a\\mid c$，即 $aRc$。\n\n因此此關係具有自反、反對稱、傳遞性，不具對稱性。",
    "rubric": [
      {
        "score": 3,
        "description": "正確判定自反，並以任意正整數 $a$ 滿足 $a=a\\cdot1$、故 $a\\mid a$ 證明。"
      },
      {
        "score": 3,
        "description": "正確判定不對稱，並給出 $2\\mid4$ 但 $4\\nmid2$，或其他有效反例。"
      },
      {
        "score": 3,
        "description": "正確判定反對稱，並由正整數的互相整除推出 $a=b$；例如使用正整數商 $m,n$ 滿足 $mn=1$。"
      },
      {
        "score": 3,
        "description": "正確判定傳遞，並由 $b=ma$、$c=nb$ 推出 $c=(nm)a$、故 $a\\mid c$，或給出等價的一般證明。"
      }
    ],
    "points": 12,
    "referenceAnswer": "Reflexive：是；symmetric：否；antisymmetric：是；transitive：是。",
    "gradingRubric": [
      {
        "id": "r1",
        "points": 3,
        "description": "正確判定自反，並以任意正整數 $a$ 滿足 $a=a\\cdot1$、故 $a\\mid a$ 證明。"
      },
      {
        "id": "r2",
        "points": 3,
        "description": "正確判定不對稱，並給出 $2\\mid4$ 但 $4\\nmid2$，或其他有效反例。"
      },
      {
        "id": "r3",
        "points": 3,
        "description": "正確判定反對稱，並由正整數的互相整除推出 $a=b$；例如使用正整數商 $m,n$ 滿足 $mn=1$。"
      },
      {
        "id": "r4",
        "points": 3,
        "description": "正確判定傳遞，並由 $b=ma$、$c=nb$ 推出 $c=(nm)a$、故 $a\\mid c$，或給出等價的一般證明。"
      }
    ]
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q5",
    "questionIndex": 9,
    "type": "calculation",
    "prompt": "### 5.（14 分）\n$A=\\{1,2,3,4\\}$\n\n(a) $A$ 上共有幾個對稱 (symmetric) 關係？\n\n(b) $A$ 上共有幾個反對稱 (antisymmetric) 關係？\n\n請寫計算過程或說明理由。",
    "hint": null,
    "solution": "任何 $A$ 上的關係都是 $A\\times A$ 的子集合。四個對角有序對為 $(1,1),(2,2),(3,3),(4,4)$；相異元素構成 $\\binom{4}{2}=6$ 個無序對，每個無序對 $\\{a,b\\}$ 對應 $(a,b)$ 與 $(b,a)$。\n\n**(a) 對稱關係。** 對角有序對的反向仍是它自己，無論包含或不包含皆不違反對稱性，因此每個對角有序對有兩種選擇，共 $2^4$ 種。對每個無序對 $\\{a,b\\}$，對稱性要求 $(a,b)$、$(b,a)$ 同時包含或同時不包含，恰有兩種選擇；六個無序對共 $2^6$ 種。這些選擇彼此獨立，故\n\n$$\n2^4\\cdot2^6=2^{10}=1024.\n$$\n\n**(b) 反對稱關係。** 反對稱性只要求：若 $aRb$ 且 $bRa$，則 $a=b$。對角有序對可以任意包含或不包含，共 $2^4$ 種；這不要求關係自反。對每個相異元素的無序對 $\\{a,b\\}$，不能同時包含兩個方向，但可有三種選擇：兩者皆不包含、只包含 $(a,b)$、只包含 $(b,a)$。六個無序對的選擇獨立，因此\n\n$$\n2^4\\cdot3^6=16\\cdot729=11664.\n$$",
    "rubric": [
      {
        "score": 2,
        "description": "(a) 說明四個對角有序對各可任意包含或不包含，產生 $2^4$ 種選擇。"
      },
      {
        "score": 3,
        "description": "(a) 辨認六個相異元素的無序對，每對的兩個方向必須同時包含或同時不包含，產生 $2^6$ 種選擇。"
      },
      {
        "score": 2,
        "description": "(a) 正確相乘得到 $2^{10}=1024$ 個對稱關係。"
      },
      {
        "score": 2,
        "description": "(b) 說明反對稱不要求自反，四個對角有序對各有兩種選擇，產生 $2^4$ 種。"
      },
      {
        "score": 3,
        "description": "(b) 辨認六個無序對，每對僅允許皆不包含、只包含正向、只包含反向三種選擇，產生 $3^6$ 種。"
      },
      {
        "score": 2,
        "description": "(b) 正確相乘得到 $2^4\\cdot3^6=11664$ 個反對稱關係。"
      }
    ],
    "points": 14,
    "referenceAnswer": "(a) $2^{10}=1024$ 個對稱關係。\n\n(b) $2^4\\cdot3^6=11664$ 個反對稱關係。",
    "gradingRubric": [
      {
        "id": "r1",
        "points": 2,
        "description": "(a) 說明四個對角有序對各可任意包含或不包含，產生 $2^4$ 種選擇。"
      },
      {
        "id": "r2",
        "points": 3,
        "description": "(a) 辨認六個相異元素的無序對，每對的兩個方向必須同時包含或同時不包含，產生 $2^6$ 種選擇。"
      },
      {
        "id": "r3",
        "points": 2,
        "description": "(a) 正確相乘得到 $2^{10}=1024$ 個對稱關係。"
      },
      {
        "id": "r4",
        "points": 2,
        "description": "(b) 說明反對稱不要求自反，四個對角有序對各有兩種選擇，產生 $2^4$ 種。"
      },
      {
        "id": "r5",
        "points": 3,
        "description": "(b) 辨認六個無序對，每對僅允許皆不包含、只包含正向、只包含反向三種選擇，產生 $3^6$ 種。"
      },
      {
        "id": "r6",
        "points": 2,
        "description": "(b) 正確相乘得到 $2^4\\cdot3^6=11664$ 個反對稱關係。"
      }
    ]
  },
  {
    "quizId": "discrete-math",
    "revision": "1",
    "questionId": "q6",
    "questionIndex": 10,
    "type": "calculation",
    "prompt": "### 6.（12 分）\n計算 $x_1+x_2+x_3+x_4=18$ 非負整數解的個數，而且加上限制 $x_i\\le7$，對所有 $1\\le i\\le4$。\n\n請寫計算過程或說明理由。",
    "hint": null,
    "solution": "先不加上界，四個非負整數總和為 18 的解有\n\n$$\n\\binom{18+4-1}{4-1}=\\binom{21}{3}=1330\n$$\n\n個。令 $E_i$ 為 $x_i\\ge8$ 的違規解集合。\n\n**一個變數違規。** 固定 $i$，令 $y_i=x_i-8\\ge0$，其他變數不變，新的總和為 $18-8=10$，故\n\n$$\n|E_i|=\\binom{10+3}{3}=\\binom{13}{3}=286.\n$$\n\n四個變數的單一違規計數總和為 $4\\cdot286=1144$。\n\n**兩個變數同時違規。** 固定 $i\\ne j$，對這兩個變數各減 8，剩餘總和為 $18-16=2$，故\n\n$$\n|E_i\\cap E_j|=\\binom{2+3}{3}=\\binom{5}{3}=10.\n$$\n\n共有 $\\binom{4}{2}=6$ 對，兩兩交集總和為 $6\\cdot10=60$。\n\n**三個或四個變數同時違規。** 三個變數各至少為 8 時，總和至少為 24，已超過 18；故所有三重交集及四重交集皆為空。\n\n因此由容斥原理，符合全部上界的解數為\n\n$$\n\\binom{21}{3}-4\\binom{13}{3}+\\binom{4}{2}\\binom{5}{3}\n=1330-1144+60=246.\n$$\n\n另可驗算：令 $z_i=7-x_i$，則 $0\\le z_i\\le7$ 且 $\\sum_{i=1}^{4}z_i=28-18=10$。不加上界時有 $\\binom{13}{3}=286$ 個解；每個 $z_i\\ge8$ 的違規集合有 $\\binom{5}{3}=10$ 個解，且兩個變數同時違規需總和至少 16，故交集為空。因此亦得 $286-4\\cdot10=246$。",
    "rubric": [
      {
        "score": 2,
        "description": "正確使用星與棒得到不加上界的解數 $\\binom{21}{3}=1330$。"
      },
      {
        "score": 3,
        "description": "正確將單一違規定為 $x_i\\ge8$，平移後總和為 10，得到每個集合 $\\binom{13}{3}=286$、四個集合合計 1144。"
      },
      {
        "score": 3,
        "description": "正確將兩個違規變數各減 8，得到每個交集 $\\binom{5}{3}=10$，並乘六對得到 60。"
      },
      {
        "score": 2,
        "description": "說明三個違規變數的最小總和為 24，大於 18，因此三重及四重交集皆為空。"
      },
      {
        "score": 2,
        "description": "正確使用容斥符號並算出 $1330-1144+60=246$，所有條件均被計入。"
      }
    ],
    "points": 12,
    "referenceAnswer": "$246$ 個非負整數解。",
    "gradingRubric": [
      {
        "id": "r1",
        "points": 2,
        "description": "正確使用星與棒得到不加上界的解數 $\\binom{21}{3}=1330$。"
      },
      {
        "id": "r2",
        "points": 3,
        "description": "正確將單一違規定為 $x_i\\ge8$，平移後總和為 10，得到每個集合 $\\binom{13}{3}=286$、四個集合合計 1144。"
      },
      {
        "id": "r3",
        "points": 3,
        "description": "正確將兩個違規變數各減 8，得到每個交集 $\\binom{5}{3}=10$，並乘六對得到 60。"
      },
      {
        "id": "r4",
        "points": 2,
        "description": "說明三個違規變數的最小總和為 24，大於 18，因此三重及四重交集皆為空。"
      },
      {
        "id": "r5",
        "points": 2,
        "description": "正確使用容斥符號並算出 $1330-1144+60=246$，所有條件均被計入。"
      }
    ]
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "composition",
    "questionIndex": 7,
    "type": "fill",
    "prompt": "### 關係合成\n若 $R=\\{(1,2)\\}$、$S=\\{(2,3)\\}$，請以 `(1,3)` 格式填出 $S\\circ R$ 唯一的有序對。",
    "hint": null,
    "solution": "先經 $R$ 從 $1$ 到 $2$，再經 $S$ 從 $2$ 到 $3$，所以 $S\\circ R=\\{(1,3)\\}$。",
    "rubric": [],
    "points": 2,
    "correctAnswer": "(1,3)",
    "match": "exact"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "empty-symmetric",
    "questionIndex": 6,
    "type": "true-false",
    "prompt": "### 空關係\n非空集合上的空關係 $\\varnothing$ 是對稱的。",
    "hint": null,
    "solution": "空關係沒有任何 $(a,b)$ 需要檢查，所以對稱條件真空成立。",
    "rubric": [],
    "points": 1,
    "correctAnswer": true
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "equivalence",
    "questionIndex": 3,
    "type": "fill",
    "prompt": "### 等價關係\n等價關係須自反、傳遞，還須具備哪一種性質？請填「對稱」。",
    "hint": null,
    "solution": "等價關係同時具有自反、對稱、傳遞三種性質。",
    "rubric": [],
    "points": 2,
    "correctAnswer": "對稱",
    "match": "exact"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "partial-order",
    "questionIndex": 5,
    "type": "multiple",
    "prompt": "### 偏序條件\n偏序關係必須具備哪些性質？",
    "hint": null,
    "solution": "偏序的定義是自反、反對稱、傳遞；不要求對稱。",
    "rubric": [],
    "points": 3,
    "options": [
      {
        "id": "a",
        "content": "自反"
      },
      {
        "id": "b",
        "content": "對稱"
      },
      {
        "id": "c",
        "content": "反對稱"
      },
      {
        "id": "d",
        "content": "傳遞"
      }
    ],
    "correctOptionIds": [
      "a",
      "c",
      "d"
    ]
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "reflexive",
    "questionIndex": 0,
    "type": "single",
    "prompt": "### 自反關係\n在 $X=\\{1,2\\}$ 上，$R=\\{(1,1),(2,2)\\}$ 是否自反？",
    "hint": null,
    "solution": "自反只要求 $(1,1)$ 和 $(2,2)$ 都在 $R$ 中；此關係符合。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "是，因為 $X$ 中每個元素都與自己有關係。"
      },
      {
        "id": "b",
        "content": "否，因為缺少 $(1,2)$。"
      },
      {
        "id": "c",
        "content": "否，因為缺少 $(2,1)$。"
      }
    ],
    "correctOptionId": "a"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "symmetry",
    "questionIndex": 2,
    "type": "true-false",
    "prompt": "### 對稱的定義\n若 $R$ 對稱，則對任意 $a,b$，只要 $(a,b)\\in R$，就有 $(b,a)\\in R$。",
    "hint": null,
    "solution": "這正是對稱關係的定義。",
    "rubric": [],
    "points": 1,
    "correctAnswer": true
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "transitivity",
    "questionIndex": 4,
    "type": "single",
    "prompt": "### 檢查傳遞性\n在 $X=\\{1,2,3\\}$ 上，$R=\\{(1,2),(2,3)\\}$ 是否傳遞？",
    "hint": null,
    "solution": "由 $(1,2)$ 與 $(2,3)$，傳遞性要求 $(1,3)$ 也在 $R$ 中；它並不存在。",
    "rubric": [],
    "points": 2,
    "options": [
      {
        "id": "a",
        "content": "是，因為關係中只有兩個有序對。"
      },
      {
        "id": "b",
        "content": "否，因為缺少 $(1,3)$。"
      },
      {
        "id": "c",
        "content": "否，因為缺少 $(3,1)$。"
      }
    ],
    "correctOptionId": "b"
  },
  {
    "quizId": "relations",
    "revision": "1",
    "questionId": "universal",
    "questionIndex": 1,
    "type": "multiple",
    "prompt": "### 全關係\n在 $X=\\{1,2\\}$ 上，$R=X\\times X$ 具有哪些性質？",
    "hint": null,
    "solution": "所有有序對都在 $R$ 中，因此自反、對稱且傳遞；它包含 $(1,1)$ 與 $(2,2)$，所以不反自反。",
    "rubric": [],
    "points": 3,
    "options": [
      {
        "id": "a",
        "content": "自反"
      },
      {
        "id": "b",
        "content": "對稱"
      },
      {
        "id": "c",
        "content": "傳遞"
      },
      {
        "id": "d",
        "content": "反自反"
      }
    ],
    "correctOptionIds": [
      "a",
      "b",
      "c"
    ]
  }
] as const
